-- Add sample data to not_relevant_companies
INSERT INTO public.not_relevant_companies (company_name, category) VALUES
('McDonald''s', 'Fast Food'),
('Burger King', 'Fast Food'),
('KFC', 'Fast Food'),
('Pizza Hut', 'Fast Food'),
('Starbucks', 'Coffee Shop'),
('Walmart', 'Retail'),
('Target', 'Retail'),
('Home Depot', 'Retail'),
('Best Buy', 'Electronics Retail'),
('GameStop', 'Gaming Retail'),
('Forever 21', 'Fashion Retail'),
('H&M', 'Fashion Retail'),
('Zara', 'Fashion Retail'),
('Uniqlo', 'Fashion Retail'),
('Gap', 'Fashion Retail'),
('Old Navy', 'Fashion Retail'),
('Banana Republic', 'Fashion Retail'),
('Abercrombie & Fitch', 'Fashion Retail'),
('American Eagle', 'Fashion Retail'),
('Urban Outfitters', 'Fashion Retail');

-- Add sample data to target_companies  
INSERT INTO public.target_companies (company_name, category) VALUES
('Google', 'Big Tech'),
('Microsoft', 'Big Tech'),
('Apple', 'Big Tech'),
('Meta', 'Big Tech'),
('Amazon', 'Big Tech'),
('Netflix', 'Big Tech'),
('Tesla', 'Electric Vehicles'),
('SpaceX', 'Aerospace'),
('Nvidia', 'Semiconductors'),
('Intel', 'Semiconductors'),
('AMD', 'Semiconductors'),
('Salesforce', 'Cloud/SaaS'),
('ServiceNow', 'Cloud/SaaS'),
('Workday', 'Cloud/SaaS'),
('Zoom', 'Cloud/SaaS'),
('Slack', 'Cloud/SaaS'),
('Atlassian', 'Cloud/SaaS'),
('MongoDB', 'Database'),
('Snowflake', 'Data/Analytics'),
('Databricks', 'Data/Analytics'),
('Palantir', 'Data/Analytics'),
('Unity', 'Gaming/AR/VR'),
('Epic Games', 'Gaming'),
('Roblox', 'Gaming'),
('Uber', 'Transportation'),
('Lyft', 'Transportation'),
('Airbnb', 'Travel/Hospitality'),
('DoorDash', 'Food Delivery'),
('Instacart', 'Grocery Delivery'),
('Stripe', 'Fintech'),
('Square', 'Fintech'),
('PayPal', 'Fintech'),
('Coinbase', 'Cryptocurrency'),
('Robinhood', 'Fintech'),
('Shopify', 'E-commerce'),
('Etsy', 'E-commerce'),
('eBay', 'E-commerce'),
('Zillow', 'Real Estate Tech'),
('Redfin', 'Real Estate Tech'),
('Peloton', 'Fitness Tech'),
('Mirror', 'Fitness Tech'),
('WeWork', 'Co-working'),
('Canva', 'Design Tools'),
('Figma', 'Design Tools'),
('Adobe', 'Creative Software'),
('Autodesk', 'Design Software'),
('Twilio', 'Communications API'),
('SendGrid', 'Email Services'),
('Mailchimp', 'Marketing Tools'),
('HubSpot', 'Marketing/CRM'),
('Zendesk', 'Customer Service'),
('Intercom', 'Customer Service'),
('Notion', 'Productivity'),
('Airtable', 'Database/Productivity'),
('Asana', 'Project Management'),
('Monday.com', 'Project Management'),
('Trello', 'Project Management'),
('Jira', 'Project Management'),
('GitLab', 'DevTools'),
('GitHub', 'DevTools'),
('Docker', 'DevTools'),
('HashiCorp', 'DevTools'),
('Datadog', 'Monitoring'),
('New Relic', 'Monitoring'),
('Splunk', 'Data Analytics'),
('Elastic', 'Search/Analytics');

-- Add sample data to top_universities
INSERT INTO public.top_universities (university_name, country) VALUES
-- Israeli Universities
('Technion - Israel Institute of Technology', 'Israel'),
('Hebrew University of Jerusalem', 'Israel'),
('Tel Aviv University', 'Israel'),
('Weizmann Institute of Science', 'Israel'),
('Ben-Gurion University of the Negev', 'Israel'),
('Bar-Ilan University', 'Israel'),
('University of Haifa', 'Israel'),
('Open University of Israel', 'Israel'),
('Ariel University', 'Israel'),
('IDC Herzliya', 'Israel'),

-- US Universities (Top Tier)
('Harvard University', 'United States'),
('Stanford University', 'United States'),
('Massachusetts Institute of Technology', 'United States'),
('California Institute of Technology', 'United States'),
('University of California, Berkeley', 'United States'),
('Princeton University', 'United States'),
('Yale University', 'United States'),
('Columbia University', 'United States'),
('University of Chicago', 'United States'),
('Cornell University', 'United States'),
('University of Pennsylvania', 'United States'),
('Dartmouth College', 'United States'),
('Brown University', 'United States'),
('Carnegie Mellon University', 'United States'),
('Northwestern University', 'United States'),
('Duke University', 'United States'),
('Johns Hopkins University', 'United States'),
('University of California, Los Angeles', 'United States'),
('University of Michigan', 'United States'),
('New York University', 'United States'),
('University of Southern California', 'United States'),
('Georgia Institute of Technology', 'United States'),
('University of Illinois at Urbana-Champaign', 'United States'),
('University of Washington', 'United States'),
('University of Texas at Austin', 'United States'),

-- UK Universities
('University of Oxford', 'United Kingdom'),
('University of Cambridge', 'United Kingdom'),
('Imperial College London', 'United Kingdom'),
('London School of Economics', 'United Kingdom'),
('University College London', 'United Kingdom'),
('King''s College London', 'United Kingdom'),
('University of Edinburgh', 'United Kingdom'),
('University of Manchester', 'United Kingdom'),
('University of Warwick', 'United Kingdom'),
('London Business School', 'United Kingdom'),

-- Other International
('ETH Zurich', 'Switzerland'),
('University of Toronto', 'Canada'),
('McGill University', 'Canada'),
('University of British Columbia', 'Canada'),
('Australian National University', 'Australia'),
('University of Melbourne', 'Australia'),
('University of Sydney', 'Australia'),
('National University of Singapore', 'Singapore'),
('Nanyang Technological University', 'Singapore'),
('University of Tokyo', 'Japan'),
('Kyoto University', 'Japan'),
('Seoul National University', 'South Korea'),
('KAIST', 'South Korea'),
('Peking University', 'China'),
('Tsinghua University', 'China'),
('Hong Kong University of Science and Technology', 'Hong Kong'),
('University of Hong Kong', 'Hong Kong'),
('INSEAD', 'France/Singapore'),
('École Polytechnique', 'France'),
('Sorbonne University', 'France'),
('Technical University of Munich', 'Germany'),
('Max Planck Institute', 'Germany'),
('Indian Institute of Technology Bombay', 'India'),
('Indian Institute of Technology Delhi', 'India'),
('Indian Institute of Science', 'India');