-- Clear existing not relevant companies and add the updated list from PDF
DELETE FROM public.not_relevant_companies;

-- Insert all companies from the Not Relevant Companies PDF
INSERT INTO public.not_relevant_companies (company_name, category) VALUES
-- From Page 1
('Isracard', 'Financial Services'),
('Matrix', 'Consulting'),
('Harel Insurance & Finance', 'Insurance'),
('Ness Technologies', 'Software House'),
('Bank Leumi', 'Banking'),
('GAV Systems', 'Software House'),
('Amdocs', 'Software House'),
('Log-On Software', 'Software House'),
('Sapiens', 'Software House'),
('Aman Group', 'Software House'),
('NICE', 'Software House'),
('Maccabi Health care Services', 'Healthcare'),
('Zap Group', 'Retail'),
('Clalit Health Services', 'Healthcare'),
('Bank Hapoalim', 'Banking'),
('Israel Tax Authority', 'Government'),
('Discount Bank', 'Banking'),
('Infanity Labs', 'Software House'),
('Experis Israel', 'Consulting'),
('Sapiens International', 'Software House'),
('Magic Software Enterprises', 'Software House'),
('Ethernity Networks', 'Software House'),
('Elad Software Systems', 'Software House'),
('Mizrahi-Tefahot Bank', 'Banking'),
('Migdal Insurance', 'Insurance'),
('Menora Mivtachim', 'Insurance'),
('Clal Insurance', 'Insurance'),
('Taldor', 'Software House'),
('Bynet Data Communications', 'Software House'),
('Hachshara Insurance Company', 'Insurance'),
-- From Page 2
('Psagot Investment House', 'Financial Services'),
('Max It Finance', 'Financial Services'),
('bizi', 'Software House'),
('Sqlink', 'Software House'),
('CGS Israel (Computer Generated Solutions)', 'Software House'),
('Commit', 'Software House'),
('CodeOasis LTD', 'Software House'),
('Inetex LTD', 'Software House'),
('EPAM Systems', 'Software House'),
('Software AG Israel', 'Software House'),
('ICTBIT Solutions', 'Software House'),
('YIT - Yedioth Tech', 'Software House'),
('Yad 2', 'Real Estate'),
('Arrow ECS Israel', 'Software House'),
('Fayrix', 'Software House'),
('Elbit Systems', 'Defense'),
('Intersog Israel', 'Software House'),
('Testview', 'Software House'),
('Adecco Israel', 'Consulting'),
-- From Page 3
('Check Point Software', 'Cybersecurity'),
('D.I.T – Israel', 'Software House'),
('Comverse', 'Software House'),
('HBA System Integrators', 'Software House'),
('Philips', 'Healthcare'),
('Bank of Israel', 'Banking'),
('HOT', 'Telecommunications'),
('YES', 'Telecommunications'),
('FIBI', 'Banking'),
('Bank Yahav', 'Banking'),
('Bank of Jerusalem', 'Banking'),
('Bank Masad', 'Banking'),
('Clal Insurance & Finance', 'Insurance'),
('Mako', 'Media'),
('Migdal Group', 'Insurance'),
('Direct Insurance', 'Insurance'),
('Ayalon Insurance & Finance', 'Insurance'),
('The Phoenix Insurance', 'Insurance'),
('Hachshara Insurance', 'Insurance'),
('Wobi Ltd', 'Software House'),
('InsurTech Israel', 'Insurance'),
('VFR', 'Software House'),
-- From Page 4
('KPMG Israel', 'Consulting'),
('IEC - Israel Electric Corporation', 'Utilities'),
('HQ', 'Software House'),
('supercom', 'Software House'),
('Yael - CloudTech', 'Software House'),
('compie_technologies', 'Software House'),
('cisco', 'Networking'),
('one1-systems', 'Software House'),
('cellopark-israel', 'Software House'),
('NICE Systems', 'Software House'),
('michlol-services-application', 'Software House'),
('Rafael Advanced Defense Systems', 'Defense'),
('Non-profit Organization', 'Non-Profit'),
('applift-consulting', 'Consulting'),
('botika-io', 'Software House'),
('advanced-parking-limited', 'Software House'),
('Mercava', 'Software House'),
('Almog Software Solutions', 'Software House'),
('memo-global', 'Software House'),
('rayzone-group', 'Software House'),
('IBI Capital LTD', 'Financial Services'),
('Sapiens DECISION', 'Software House'),
('Yedioth Ahronoth', 'Media'),
('Unitask Group', 'Software House'),
('Amarel', 'Software House'),
-- From Page 5
('MS3 Ltd', 'Software House'),
('Sela', 'Training'),
('019Mobile', 'Software House'),
('IntellForce', 'Software House'),
('Dell EMC XtremIO', 'Hardware'),
('Korentec Technologies By Yael Group', 'Software House'),
('TAG Video Systems', 'Software House'),
('Electrical Grid Monitoring, Inc.', 'Software House'),
('Xsense Ltd', 'Software House'),
('Imco Defense Division- Nir-Or Israel Ltd', 'Defense'),
('iMDsoft', 'Software House'),
('Moveo Group', 'Software House'),
('We Ankor', 'Software House'),
('InfinityLabs R&D', 'Software House'),
('PalWallet', 'FinTech'),
('G&S Banking Automation', 'Financial Services'),
('Ceva, Inc.', 'Software House'),
('BillRun Technologies Ltd.', 'Software House'),
('cellcom tv', 'Telecommunications'),
('Albar אלבר', 'Software House'),
('ENTER digital studio', 'Digital Agency'),
('Pilat Group', 'Software House'),
('TSG', 'Software House'),
('Bynet Software Systems Ltd.', 'Software House'),
('Comax smart E.R.P', 'Software House'),
('LMY R&D', 'Software House'),
('Danel Group  דנאלקבוצת', 'Software House'),
('UNIQAI Systems', 'Software House'),
('MINT - Marketing Innovation Technology', 'Software House'),
('TeleMessage, a Smarsh Company', 'Communications'),
-- From Page 6
('Omnicon Distributed Systems Ltd', 'Software House'),
('Typemock Ltd - The Unit Testing Company', 'Software House'),
('SixKeys-Boutique Business Consultancy', 'Consulting'),
('E&A Financial Software Systems LTD', 'Financial Software'),
('Yael Group', 'Software House'),
('Civil Service Commission', 'Government'),
('Priority Software', 'Software House'),
('Belong.Life', 'HealthTech'),
('Chain Reaction Ltd.', 'Software House'),
('Scadasudo Ltd', 'Software House'),
('Compulite Systems (2000) Ltd.', 'Software House'),
('Lolatech ltd', 'Software House'),
('הפנסיוניתהמסלקה', 'Financial Services'),
('Flight Medical Innovations Ltd.', 'HealthTech'),
('Zadara', 'Cloud Storage'),
('Systematics', 'Software House'),
('Acubez', 'Software House'),
('Clevaligner', 'Software House'),
('ישראלי התקנים מכון- The Standards Institution of Israel', 'Government'),
('IDOZ', 'Software House'),
('Alcon Systems Ltd', 'Software House'),
('MDClone', 'HealthTech'),
('Toga Networks-a Huawei Company', 'Networking'),
('Celeno', 'Semiconductors'),
('CTERA', 'Storage'),
('Deloitte', 'Consulting'),
('El Al', 'Airlines'),
('Gini-Apps', 'Software House'),
-- From Page 7
('John Bryce', 'Training'),
('SodaStream International, Ltd.', 'Consumer Goods'),
('Elbit Systems Israel', 'Defense'),
('Netcraft', 'Software House'),
('Tritone Technologies', 'Software House'),
('Really Great Tech', 'Software House'),
('Centerity Systems', 'Software House'),
('JLL Technologies', 'Real Estate'),
('Ex Libris', 'Software House'),
('MedDev Soft', 'Software House'),
('well-b', 'Software House'),
('Galil Software Ltd', 'Software House'),
('Ultra Information Solutions', 'Software House'),
('Israel Internet Association (ISOC-IL)', 'Non-Profit'),
('Cemantica', 'Software House'),
('Hashavim (from Hilan group)', 'Software House'),
('Hilan group', 'Software House'),
('NetApp', 'Storage'),
('NCR Retail', 'Retail Technology'),
('Pangea IT', 'Software House'),
('Pentagon 2000 Software, Inc.', 'Software House'),
('Altshuler Shaham', 'Financial Services'),
('Elpisor', 'Software House'),
('Moveo Group', 'Software House'),
('Israel Police -  ישראלמשטרת', 'Government'),
('ONE Digital', 'Software House'),
('HSP Group', 'Software House'),
('Questar Auto Technologies', 'Automotive'),
-- From Page 8
('hms - Strategic Financial IT', 'Financial Software'),
('Shareit Digital Ltd', 'Software House'),
('Furious Corp.', 'Software House'),
('KBIS - Knowledge-Based Information Systems', 'Software House'),
('IronCircle', 'Software House'),
('Ahoy! Insurance', 'Insurance'),
('BOA Ideas - Shopify Premier agency', 'Digital Agency'),
('Proggio', 'Software House'),
('Treetoscope', 'Software House'),
('Sakani.com', 'Real Estate'),
('DONE Lockers', 'Software House'),
('abra', 'Software House')
ON CONFLICT (company_name) DO NOTHING;