-- Clear existing target companies and add the updated list from PDF
DELETE FROM public.target_companies;

-- Insert all companies from the Target Companies PDF, handling duplicates
INSERT INTO public.target_companies (company_name, category) VALUES
('Wix', 'Tech'),
('Tailor Brands', 'Tech'),
('Eko', 'Tech'),
('Swimm', 'Tech'),
('Walnut', 'Tech'),
('Faye', 'InsurTech'),
('Aporia', 'Tech'),
('Gloat', 'Tech'),
('Hiredscore', 'Tech'),
('Empathy', 'Tech'),
('DataRails', 'Tech'),
('Pecan', 'Tech'),
('Similarweb', 'Tech'),
('Fireblocks', 'Cybersecurity'),
('Appsflyer', 'Tech'),
('Taboola', 'Tech'),
('MoonActive', 'Gaming'),
('Jfrog', 'Tech'),
('Yotpo', 'Tech'),
('Riskified', 'Tech'),
('Outbrain', 'Tech'),
('Logz.io', 'Tech'),
('Helios', 'Tech'),
('Via', 'Tech'),
('Simply', 'Tech'),
('Proofpoint', 'Cybersecurity'),
('Singular', 'Tech'),
('Melio', 'FinTech'),
('Unity', 'Gaming'),
('WalkMe', 'Tech'),
('Fiverr', 'Tech'),
('BigPanda', 'Tech'),
('DoiT International', 'Tech'),
('Connecteam', 'Tech'),
('Dynamic Yield', 'Tech'),
('Sisense', 'Tech'),
('F5', 'Tech'),
('Liveperson', 'Tech'),
('Papaya Gaming', 'Gaming'),
('MyHeritage', 'Tech'),
('Natural Intelligence', 'Tech'),
('Kaltura', 'Tech'),
('SundaySky', 'Tech'),
('Gett', 'Tech'),
('Trullion', 'Tech'),
('Amobee', 'Tech'),
('Tango', 'Tech'),
('Gong', 'Tech'),
('Autodesk', 'Tech'),
('Tipalti', 'FinTech'),
('Chorus.ai', 'Tech'),
('Fundbox', 'FinTech'),
('Honeybook', 'Tech'),
('Trax', 'Tech'),
('Weka.io', 'Tech'),
('Oribi', 'Tech'),
('Lemonade', 'InsurTech'),
('Rapyd', 'FinTech'),
('Pyramid Analytics', 'Tech'),
('OwnBackup', 'Tech'),
('BlueVine', 'FinTech'),
('Cybereason', 'Cybersecurity'),
('hibob', 'Tech'),
('K Health', 'HealthTech'),
('Nexar', 'Tech'),
('Snyk', 'Cybersecurity'),
('Cloudinary', 'Tech'),
('Lightricks', 'Tech'),
('Datorama', 'Tech'),
('Duda', 'Tech'),
('Vimeo', 'Tech'),
('Minute Media', 'Media'),
('Verbit', 'Tech'),
('Simplee', 'HealthTech'),
('Elementor', 'Tech'),
('Hysolate', 'Cybersecurity'),
('Intezer Labs', 'Cybersecurity'),
('Torq', 'Cybersecurity'),
('Panorays', 'Cybersecurity'),
('Sentra', 'Cybersecurity'),
('Cervello', 'Cybersecurity'),
('Grip Security', 'Cybersecurity'),
('Silverfort', 'Cybersecurity'),
('Cato', 'Cybersecurity'),
('SentinelOne', 'Cybersecurity'),
('Zscaler (Avalor)', 'Cybersecurity'),
('Apiiro', 'Cybersecurity'),
('Talon', 'Cybersecurity'),
('Palo Alto', 'Cybersecurity'),
('DeepInstinct', 'Cybersecurity'),
('At-Bay', 'InsurTech'),
('Skybox Security', 'Cybersecurity'),
('Aqua Security', 'Cybersecurity'),
('AVANAN', 'Cybersecurity'),
('Guardicore', 'Cybersecurity'),
('Orca Security', 'Cybersecurity'),
('PerimeterX', 'Cybersecurity'),
('Salt Security', 'Cybersecurity'),
('Illusive', 'Cybersecurity'),
('Cynet Security', 'Cybersecurity'),
('Perimeter 81', 'Cybersecurity'),
('CyberArk', 'Cybersecurity'),
('Forescout', 'Cybersecurity'),
('Tufin', 'Cybersecurity'),
('Argus', 'Cybersecurity'),
('Cyera', 'Cybersecurity'),
('Wiz', 'Cybersecurity'),
('Prompt Security', 'Cybersecurity'),
('Active Fence', 'Cybersecurity'),
('Apono', 'Cybersecurity'),
('Axiom Security', 'Cybersecurity'),
('Axis Security', 'Cybersecurity'),
('Axonius', 'Cybersecurity'),
('Clarity', 'Cybersecurity'),
('CYE', 'Cybersecurity'),
('CyCognito', 'Cybersecurity'),
('OX Security', 'Cybersecurity'),
('CyCode', 'Cybersecurity'),
('Cylus', 'Cybersecurity'),
('Cyren', 'Cybersecurity'),
('enSilo', 'Cybersecurity'),
('Ermetic', 'Cybersecurity'),
('GK8', 'Cybersecurity'),
('Gurdio', 'Cybersecurity'),
('Hunters', 'Cybersecurity'),
('Ionix', 'Cybersecurity'),
('Ironscales', 'Cybersecurity'),
('Jit Security', 'Cybersecurity'),
('Kodem Security', 'Cybersecurity'),
('Koverr', 'Cybersecurity'),
('Legit Security', 'Cybersecurity'),
('Mend', 'Cybersecurity'),
('Mesh Security', 'Cybersecurity'),
('Mitiga', 'Cybersecurity'),
('Morphisec', 'Cybersecurity'),
('Nagomi Security', 'Cybersecurity'),
('nsKnox', 'Cybersecurity'),
('NSO', 'Cybersecurity'),
('Oasis Security', 'Cybersecurity'),
('Oligo Security', 'Cybersecurity'),
('Otorio', 'Cybersecurity'),
('Paragon', 'Cybersecurity'),
('Pentera', 'Cybersecurity'),
('Perception Point', 'Cybersecurity'),
('Polar Security', 'Cybersecurity'),
('Seemplicity', 'Cybersecurity'),
('Semperis', 'Cybersecurity'),
('ShieldIOT', 'Cybersecurity'),
('Solvo', 'Cybersecurity'),
('Trustmi.ai', 'Cybersecurity'),
('Upstream Security', 'Cybersecurity'),
('Upwind Security', 'Cybersecurity'),
('Valence Security', 'Cybersecurity'),
('Voyager Labs', 'Cybersecurity'),
('Vulcan Security', 'Cybersecurity'),
('Zero Networks', 'Cybersecurity'),
('CheckPoint', 'Cybersecurity'),
('Algosec', 'Cybersecurity'),
('PlainID', 'Cybersecurity'),
('SafeBreach', 'Cybersecurity'),
('Cato Networks', 'Cybersecurity'),
('Transmit Security', 'Cybersecurity'),
('IntSights', 'Cybersecurity'),
('ImmunAI', 'Cybersecurity'),
('Cynet', 'Cybersecurity'),
('Duality Technologies', 'Cybersecurity'),
('Monogoto', 'Tech'),
('Veego', 'Tech'),
('Nym', 'Cybersecurity'),
('CheckMarx', 'Cybersecurity'),
('Rapid7', 'Cybersecurity'),
('WhiteSource', 'Cybersecurity'),
('Curv', 'Cybersecurity'),
('Armis', 'Cybersecurity'),
('Claroty', 'Cybersecurity'),
('Guardknox', 'Cybersecurity'),
('ThetaRay', 'Cybersecurity'),
('Deep Instinct', 'Cybersecurity'),
('BlueVoyant', 'Cybersecurity'),
('Guardz', 'Cybersecurity'),
('Laminar', 'Cybersecurity'),
('Dazz', 'Cybersecurity'),
('Medigate', 'Cybersecurity'),
('Tenable', 'Cybersecurity'),
('XM Cyber', 'Cybersecurity'),
('CrowdStrike', 'Cybersecurity'),
('Sygnia', 'Cybersecurity'),
('Cyberbit', 'Cybersecurity'),
('Mesh Payments', 'FinTech'),
('Earnix', 'FinTech'),
('Pagaya', 'FinTech'),
('Forter', 'FinTech'),
('Jones', 'FinTech'),
('Deel', 'Tech'),
('Planck', 'InsurTech'),
('Agora', 'FinTech'),
('EverC', 'FinTech'),
('Sunbit', 'FinTech'),
('Anchor', 'FinTech'),
('Anecdotes', 'Tech'),
('April', 'InsurTech'),
('Bizzabo', 'Tech'),
('Bluevine', 'FinTech'),
('Bringg', 'Tech'),
('Buildots', 'Tech'),
('Checkmarx', 'Cybersecurity'),
('Coralogix', 'Tech'),
('Fabric', 'Tech'),
('Hippo', 'InsurTech'),
('ironSource', 'Gaming'),
('Jifiti', 'FinTech'),
('Kazaplan', 'FinTech'),
('Lili', 'FinTech'),
('Lusha', 'Tech'),
('Medisafe', 'HealthTech'),
('Monday.com', 'Tech'),
('Nayax', 'FinTech'),
('Next Insurance', 'InsurTech'),
('Nielsen', 'Tech'),
('Papaya Global', 'Tech'),
('Parametrix', 'InsurTech'),
('Payoneer', 'FinTech'),
('PrimeSense', 'Tech'),
('Reali', 'PropTech'),
('Redis', 'Tech'),
('SolarEdge', 'CleanTech'),
('Spot.IM', 'Media'),
('StoreDot', 'CleanTech'),
('WeFi', 'Tech'),
('Windward', 'Tech'),
('Zebra Medical', 'HealthTech'),
('Zerto', 'Tech'),
('Zooz', 'FinTech')
ON CONFLICT (company_name) DO NOTHING;