-- Clear existing synonyms and add the complete list from PDF
DELETE FROM public.synonyms;

-- Insert all synonyms from the Synonyms Map PDF
INSERT INTO public.synonyms (canonical_term, variant_term, category) VALUES
-- Development Roles
('developer', 'engineer', 'development_roles'),
('developer', 'programmer', 'development_roles'),
('developer', 'coder', 'development_roles'),
('developer', 'dev', 'development_roles'),
('developer', 'software developer', 'development_roles'),
('developer', 'software engineer', 'development_roles'),
('developer', 'application developer', 'development_roles'),
('developer', 'web developer', 'development_roles'),
('developer', 'app developer', 'development_roles'),
('development', 'coding specialist', 'development_roles'),
('development', 'development specialist', 'development_roles'),
('engineer', 'systems engineer', 'development_roles'),
('engineer', 'technical engineer', 'development_roles'),
('engineer', 'development engineer', 'development_roles'),
('engineer', 'application engineer', 'development_roles'),
('engineer', 'solutions engineer', 'development_roles'),
('frontend', 'front-end', 'development_roles'),
('frontend', 'frontend developer', 'development_roles'),
('frontend', 'ui developer', 'development_roles'),
('frontend', 'client-side developer', 'development_roles'),
('frontend', 'react developer', 'development_roles'),
('frontend', 'vue developer', 'development_roles'),
('frontend', 'angular developer', 'development_roles'),
('frontend', 'javascript developer', 'development_roles'),
('frontend', 'ui/ux developer', 'development_roles'),
('frontend', 'interface developer', 'development_roles'),
('backend', 'back-end', 'development_roles'),
('backend', 'backend developer', 'development_roles'),
('backend', 'server-side developer', 'development_roles'),
('backend', 'api developer', 'development_roles'),
('backend', 'node.js developer', 'development_roles'),
('backend', 'nodejs developer', 'development_roles'),
('backend', 'express developer', 'development_roles'),
('backend', 'nestjs developer', 'development_roles'),
('backend', 'server developer', 'development_roles'),
('backend', 'database developer', 'development_roles'),
('backend', 'microservices developer', 'development_roles'),
('backend', 'rest api developer', 'development_roles'),
('fullstack', 'full-stack', 'development_roles'),
('fullstack', 'fullstack developer', 'development_roles'),
('fullstack', 'full stack engineer', 'development_roles'),
('fullstack', 'frontend + backend', 'development_roles'),
('fullstack', 'react + node.js', 'development_roles'),
('fullstack', 'end-to-end developer', 'development_roles'),
('fullstack', 'complete stack developer', 'development_roles'),
('fullstack', 'universal developer', 'development_roles'),

-- Operations & Infrastructure
('devops', 'infrastructure engineer', 'operations'),
('devops', 'site reliability engineer', 'operations'),
('devops', 'sre', 'operations'),
('devops', 'platform engineer', 'operations'),
('devops', 'ci/cd engineer', 'operations'),
('devops', 'kubernetes engineer', 'operations'),
('devops', 'docker specialist', 'operations'),
('devops', 'cloud engineer', 'operations'),
('devops', 'automation engineer', 'operations'),
('devops', 'deployment engineer', 'operations'),
('devops', 'infrastructure specialist', 'operations'),

-- Data Roles
('data engineer', 'data scientist', 'data_roles'),
('data engineer', 'data analyst', 'data_roles'),
('data engineer', 'analytics engineer', 'data_roles'),
('data engineer', 'bi developer', 'data_roles'),
('data engineer', 'big data engineer', 'data_roles'),
('data engineer', 'dwh developer', 'data_roles'),
('data engineer', 'sql developer', 'data_roles'),
('data engineer', 'database specialist', 'data_roles'),
('data engineer', 'data specialist', 'data_roles'),
('data engineer', 'etl developer', 'data_roles'),
('data analyst', 'business analyst', 'data_roles'),
('data analyst', 'bi analyst', 'data_roles'),
('data analyst', 'business intelligence analyst', 'data_roles'),
('data analyst', 'research analyst', 'data_roles'),
('data analyst', 'reporting analyst', 'data_roles'),
('data analyst', 'insights analyst', 'data_roles'),
('data analyst', 'metrics analyst', 'data_roles'),
('data analyst', 'quantitative analyst', 'data_roles'),

-- Management Roles
('product manager', 'pm', 'management'),
('product manager', 'product owner', 'management'),
('product manager', 'po', 'management'),
('product manager', 'product lead', 'management'),
('product manager', 'product director', 'management'),
('product manager', 'product strategy', 'management'),
('product manager', 'product marketing manager', 'management'),
('product manager', 'product specialist', 'management'),
('manager', 'lead', 'management'),
('manager', 'director', 'management'),
('manager', 'head', 'management'),
('manager', 'team lead', 'management'),
('manager', 'team manager', 'management'),
('manager', 'supervisor', 'management'),
('manager', 'group manager', 'management'),
('manager', 'department head', 'management'),
('manager', 'engineering manager', 'management'),
('manager', 'technical manager', 'management'),
('team lead', 'tech lead', 'management'),
('team lead', 'technical lead', 'management'),
('team lead', 'lead developer', 'management'),
('team lead', 'senior developer', 'management'),
('team lead', 'squad lead', 'management'),
('team lead', 'development lead', 'management'),
('team lead', 'engineering lead', 'management'),
('architect', 'senior architect', 'management'),
('architect', 'chief architect', 'management'),
('cto', 'chief technology officer', 'management'),
('cto', 'head of technology', 'management'),
('cto', 'tech director', 'management'),
('cto', 'vp of engineering', 'management'),
('cto', 'head of engineering', 'management'),
('cto', 'technology lead', 'management'),
('cto', 'chief technical officer', 'management'),

-- Company Types
('startup', 'seed stage', 'company_types'),
('startup', 'series a', 'company_types'),
('startup', 'series b', 'company_types'),
('startup', 'vc-backed', 'company_types'),
('startup', 'venture-backed', 'company_types'),
('startup', 'stealth mode', 'company_types'),
('startup', 'pre-ipo', 'company_types'),
('startup', 'scale-up', 'company_types'),
('startup', 'growth stage', 'company_types'),
('fintech', 'financial services', 'company_types'),
('fintech', 'financial technology', 'company_types'),
('fintech', 'payments', 'company_types'),
('fintech', 'banking', 'company_types'),
('fintech', 'insurance', 'company_types'),
('fintech', 'crypto', 'company_types'),
('fintech', 'blockchain', 'company_types'),
('fintech', 'insurtech', 'company_types'),
('fintech', 'regtech', 'company_types'),
('fintech', 'wealthtech', 'company_types'),
('fintech', 'lending', 'company_types'),
('fintech', 'trading', 'company_types'),

-- Technologies - AI/ML
('ai', 'artificial intelligence', 'technologies'),
('ai', 'machine learning', 'technologies'),
('ai', 'ml', 'technologies'),
('ai', 'deep learning', 'technologies'),
('ai', 'neural networks', 'technologies'),
('ai', 'nlp', 'technologies'),
('ai', 'natural language processing', 'technologies'),
('ai', 'computer vision', 'technologies'),
('ai', 'data science', 'technologies'),
('ai', 'predictive analytics', 'technologies'),
('machine learning', 'ml', 'technologies'),
('machine learning', 'deep learning', 'technologies'),
('machine learning', 'neural networks', 'technologies'),
('machine learning', 'predictive modeling', 'technologies'),
('machine learning', 'statistical modeling', 'technologies'),
('machine learning', 'data mining', 'technologies'),

-- Technologies - Cloud
('cloud', 'cloud computing', 'technologies'),
('cloud', 'aws', 'technologies'),
('cloud', 'amazon web services', 'technologies'),
('cloud', 'azure', 'technologies'),
('cloud', 'microsoft azure', 'technologies'),
('cloud', 'gcp', 'technologies'),
('cloud', 'google cloud platform', 'technologies'),
('cloud', 'cloud services', 'technologies'),
('cloud', 'cloud infrastructure', 'technologies'),
('cloud', 'serverless', 'technologies'),
('cloud', 'iaas', 'technologies'),
('cloud', 'paas', 'technologies'),
('cloud', 'saas', 'technologies'),

-- Technologies - Mobile
('mobile', 'mobile development', 'technologies'),
('mobile', 'ios development', 'technologies'),
('mobile', 'android development', 'technologies'),
('mobile', 'react native', 'technologies'),
('mobile', 'flutter', 'technologies'),
('mobile', 'mobile apps', 'technologies'),
('mobile', 'mobile applications', 'technologies'),
('mobile', 'app development', 'technologies'),
('mobile', 'native development', 'technologies'),
('mobile', 'hybrid development', 'technologies'),

-- Experience Levels
('senior', 'experienced', 'experience_levels'),
('senior', 'expert', 'experience_levels'),
('senior', 'lead', 'experience_levels'),
('senior', 'principal', 'experience_levels'),
('senior', 'staff', 'experience_levels'),
('senior', 'advanced', 'experience_levels'),
('senior', 'seasoned', 'experience_levels'),
('senior', 'veteran', 'experience_levels'),
('senior', 'specialist', 'experience_levels'),
('junior', 'entry-level', 'experience_levels'),
('junior', 'beginner', 'experience_levels'),
('junior', 'trainee', 'experience_levels'),
('junior', 'intern', 'experience_levels'),
('junior', 'associate', 'experience_levels'),
('junior', 'graduate', 'experience_levels'),
('junior', 'new grad', 'experience_levels'),
('junior', 'early career', 'experience_levels'),
('junior', 'apprentice', 'experience_levels'),

-- Programming Languages & Skills
('python', 'py', 'skills'),
('python', 'python3', 'skills'),
('python', 'python2', 'skills'),
('python', 'python programming', 'skills'),
('javascript', 'js', 'skills'),
('javascript', 'ecmascript', 'skills'),
('javascript', 'es6', 'skills'),
('typescript', 'ts', 'skills'),
('typescript', 'type script', 'skills'),
('react', 'reactjs', 'skills'),
('react', 'react.js', 'skills'),
('angular', 'angularjs', 'skills'),
('vue.js', 'vue', 'skills'),
('vue.js', 'vuejs', 'skills'),
('node.js', 'node', 'skills'),
('node.js', 'nodejs', 'skills'),
('express.js', 'express', 'skills'),
('next.js', 'nextjs', 'skills'),
('nuxt.js', 'nuxt', 'skills'),
('html', 'html5', 'skills'),
('css', 'css3', 'skills'),
('css', 'cascading style sheets', 'skills'),
('sass', 'scss', 'skills'),
('tailwind css', 'tailwind', 'skills'),
('bootstrap', 'bootstrap framework', 'skills'),
('sql', 'structured query language', 'skills'),
('sql', 'mysql', 'skills'),
('sql', 'postgresql', 'skills'),
('sql', 'ms sql', 'skills'),
('nosql', 'mongodb', 'skills'),
('nosql', 'cassandra', 'skills'),
('nosql', 'couchdb', 'skills'),
('nosql', 'dynamodb', 'skills'),
('graphql', 'graph ql', 'skills'),
('rest api', 'rest', 'skills'),
('rest api', 'restful api', 'skills'),
('soap api', 'soap', 'skills'),
('tensorflow', 'tf', 'skills'),
('tensorflow', 'tensor flow', 'skills'),
('pytorch', 'torch', 'skills'),
('pytorch', 'py torch', 'skills'),
('scikit-learn', 'sklearn', 'skills'),
('jupyter notebook', 'jupyter', 'skills'),
('jupyter notebook', 'ipython notebook', 'skills'),
('google colab', 'colab', 'skills'),

-- Job Titles
('project manager', 'pm', 'titles'),
('project manager', 'project lead', 'titles'),
('project manager', 'delivery manager', 'titles'),
('devops engineer', 'site reliability engineer', 'titles'),
('devops engineer', 'sre', 'titles'),
('backend developer', 'backend engineer', 'titles'),
('backend developer', 'server-side developer', 'titles'),
('frontend developer', 'front end engineer', 'titles'),
('frontend developer', 'ui developer', 'titles'),
('full stack developer', 'fullstack engineer', 'titles'),
('full stack developer', 'full stack engineer', 'titles'),
('qa engineer', 'quality assurance engineer', 'titles'),
('qa engineer', 'test engineer', 'titles'),
('ux designer', 'user experience designer', 'titles'),
('ui designer', 'user interface designer', 'titles'),
('business analyst', 'ba', 'titles'),
('solutions architect', 'sa', 'titles'),
('systems administrator', 'sysadmin', 'titles'),
('network engineer', 'neteng', 'titles'),
('machine learning engineer', 'ml engineer', 'titles'),
('machine learning engineer', 'ai engineer', 'titles'),
('ai researcher', 'artificial intelligence researcher', 'titles'),
('data scientist', 'ds', 'titles'),
('data scientist', 'data science specialist', 'titles'),
('data scientist', 'machine learning scientist', 'titles'),
('software engineer', 'software developer', 'titles'),
('cloud architect', 'cloud engineer', 'titles'),
('cloud architect', 'solutions architect', 'titles'),
('security analyst', 'cyber analyst', 'titles'),
('security analyst', 'infosec analyst', 'titles'),

-- Tools & Frameworks
('docker', 'containers', 'tools'),
('docker', 'docker engine', 'tools'),
('kubernetes', 'k8s', 'tools'),
('kubernetes', 'container orchestration', 'tools'),
('terraform', 'iac', 'tools'),
('terraform', 'infrastructure as code', 'tools'),
('jenkins', 'ci/cd', 'tools'),
('jenkins', 'jenkins pipeline', 'tools'),
('git', 'git version control', 'tools'),
('github', 'github', 'tools'),
('gitlab', 'gitlab', 'tools'),
('devops', 'continuous integration', 'tools'),
('devops', 'continuous deployment', 'tools'),
('agile', 'agile methodology', 'tools'),
('scrum', 'scrum framework', 'tools'),
('linux', 'unix', 'tools'),
('linux', 'gnu/linux', 'tools'),
('bash', 'shell scripting', 'tools'),
('bash', 'bash script', 'tools'),

-- Domains
('embedded systems', 'embedded', 'domains'),
('embedded systems', 'firmware', 'domains'),
('firmware', 'fw', 'domains'),
('firmware', 'embedded firmware', 'domains'),
('multithreading', 'multi threading', 'domains'),
('multithreading', 'multi-threading', 'domains'),
('oop', 'object oriented', 'domains'),
('oop', 'object-oriented programming', 'domains'),
('storage', 'storage systems', 'domains'),
('storage', 'flash storage', 'domains'),
('algorithms', 'algorithm design', 'domains'),
('algorithms', 'data structures', 'domains'),
('big data', 'data engineering', 'domains'),
('big data', 'data pipelines', 'domains'),
('analytics', 'data analytics', 'domains'),
('analytics', 'data analysis', 'domains'),
('real time', 'real-time systems', 'domains'),
('real time', 'rt', 'domains'),
('testing', 'qa', 'domains'),
('testing', 'quality assurance', 'domains'),
('security', 'cybersecurity', 'domains'),
('security', 'infosec', 'domains'),
('payments', 'fintech', 'domains'),
('payments', 'payment systems', 'domains'),
('marketing tech', 'martech', 'domains'),
('marketing tech', 'attribution', 'domains'),

-- Experience Years
('15+ years experience', '15 years', 'experience'),
('15+ years experience', '16 years', 'experience'),
('15+ years experience', '17 years', 'experience'),
('15+ years experience', 'veteran', 'experience'),
('10-15 years experience', '10 years', 'experience'),
('10-15 years experience', '11 years', 'experience'),
('10-15 years experience', '12 years', 'experience'),
('10-15 years experience', '13 years', 'experience'),
('10-15 years experience', '14 years', 'experience'),
('5-10 years experience', '5 years', 'experience'),
('5-10 years experience', '6 years', 'experience'),
('5-10 years experience', '7 years', 'experience'),
('5-10 years experience', '8 years', 'experience'),
('5-10 years experience', '9 years', 'experience'),
('0-5 years experience', 'junior', 'experience'),
('0-5 years experience', 'entry level', 'experience'),
('0-5 years experience', 'graduate', 'experience'),

-- Specific Companies
('western digital', 'wd', 'companies'),
('western digital', 'sandisk', 'companies'),
('jfrog', 'j frog', 'companies'),
('jfrog', 'artifactory', 'companies'),
('appsflyer', 'apps flyer', 'companies')
ON CONFLICT (canonical_term, variant_term) DO NOTHING;