-- Insert target companies
INSERT INTO public.target_companies (company_name, category) VALUES
-- Technology Companies
('Microsoft', 'Technology'),
('Google', 'Technology'),
('Apple', 'Technology'),
('Amazon', 'Technology'),
('Meta', 'Technology'),
('Netflix', 'Technology'),
('Tesla', 'Technology'),
('NVIDIA', 'Technology'),
('Oracle', 'Technology'),
('Salesforce', 'Technology'),
('Adobe', 'Technology'),
('IBM', 'Technology'),
('Intel', 'Technology'),
('Cisco', 'Technology'),
('VMware', 'Technology'),
('ServiceNow', 'Technology'),
('Snowflake', 'Technology'),
('Databricks', 'Technology'),
('Palantir', 'Technology'),
('Unity', 'Technology'),
('Zoom', 'Technology'),
-- Israeli Tech Companies
('Wix', 'Israeli Tech'),
('Check Point', 'Israeli Tech'),
('CyberArk', 'Israeli Tech'),
('Nice', 'Israeli Tech'),
('Amdocs', 'Israeli Tech'),
('Teva', 'Israeli Tech'),
('Rafael', 'Israeli Tech'),
('Elbit Systems', 'Israeli Tech'),
('Given Imaging', 'Israeli Tech'),
('Mobileye', 'Israeli Tech'),
('Varonis', 'Israeli Tech'),
('SentinelOne', 'Israeli Tech'),
('Fiverr', 'Israeli Tech'),
('JFrog', 'Israeli Tech'),
('IronSource', 'Israeli Tech'),
('Playtika', 'Israeli Tech'),
('Outbrain', 'Israeli Tech'),
('Taboola', 'Israeli Tech'),
-- Financial Services
('Goldman Sachs', 'Financial Services'),
('JPMorgan Chase', 'Financial Services'),
('Morgan Stanley', 'Financial Services'),
('BlackRock', 'Financial Services'),
('Visa', 'Financial Services'),
('Mastercard', 'Financial Services'),
('PayPal', 'Financial Services'),
('Stripe', 'Financial Services'),
('Fidelity', 'Financial Services'),
('Charles Schwab', 'Financial Services'),
-- Consulting
('McKinsey & Company', 'Consulting'),
('Boston Consulting Group', 'Consulting'),
('Bain & Company', 'Consulting'),
('Deloitte', 'Consulting'),
('PwC', 'Consulting'),
('EY', 'Consulting'),
('KPMG', 'Consulting'),
('Accenture', 'Consulting'),
-- Startups
('OpenAI', 'AI/ML'),
('Anthropic', 'AI/ML'),
('Scale AI', 'AI/ML'),
('Hugging Face', 'AI/ML'),
('Cohere', 'AI/ML'),
('Stability AI', 'AI/ML'),
('Midjourney', 'AI/ML'),
('Character.AI', 'AI/ML'),
('Perplexity', 'AI/ML'),
('Runway', 'AI/ML');

-- Insert top universities
INSERT INTO public.top_universities (university_name, country) VALUES
-- Israeli Universities
('Hebrew University of Jerusalem', 'Israel'),
('Tel Aviv University', 'Israel'),
('Technion - Israel Institute of Technology', 'Israel'),
('Weizmann Institute of Science', 'Israel'),
('Ben-Gurion University of the Negev', 'Israel'),
('Bar-Ilan University', 'Israel'),
('University of Haifa', 'Israel'),
('Ariel University', 'Israel'),

-- US Universities - Ivy League
('Harvard University', 'United States'),
('Yale University', 'United States'),
('Princeton University', 'United States'),
('Columbia University', 'United States'),
('University of Pennsylvania', 'United States'),
('Dartmouth College', 'United States'),
('Brown University', 'United States'),
('Cornell University', 'United States'),

-- US Universities - Top Tech Schools
('Stanford University', 'United States'),
('Massachusetts Institute of Technology', 'United States'),
('California Institute of Technology', 'United States'),
('Carnegie Mellon University', 'United States'),
('University of California Berkeley', 'United States'),
('Georgia Institute of Technology', 'United States'),
('University of Illinois Urbana-Champaign', 'United States'),
('University of Washington', 'United States'),
('University of Michigan', 'United States'),
('University of Texas at Austin', 'United States'),

-- UK Universities
('University of Oxford', 'United Kingdom'),
('University of Cambridge', 'United Kingdom'),
('Imperial College London', 'United Kingdom'),
('London School of Economics', 'United Kingdom'),
('University College London', 'United Kingdom'),
('King''s College London', 'United Kingdom'),
('University of Edinburgh', 'United Kingdom'),
('University of Manchester', 'United Kingdom'),

-- European Universities
('ETH Zurich', 'Switzerland'),
('EPFL', 'Switzerland'),
('Technical University of Munich', 'Germany'),
('RWTH Aachen University', 'Germany'),
('University of Amsterdam', 'Netherlands'),
('Delft University of Technology', 'Netherlands'),
('KTH Royal Institute of Technology', 'Sweden'),
('Technical University of Denmark', 'Denmark');