-- Clear existing target companies and add the complete list from PDF
DELETE FROM public.target_companies;

-- Insert all unique companies from the Target Companies PDF
INSERT INTO public.target_companies (company_name, category) VALUES
-- From Page 1
('Wix', 'Tech'),
('Tailor Brands', 'Tech'),
('Eko', 'Tech'),
('Swimm', 'Tech'),
('Walnut', 'Tech'),
('Faye', 'InsurTech'),
('Aporia', 'Tech'),
('Gloat', 'Tech'),
('Hiredscore', 'Tech'),
('Empathy', 'Tech'),
('DataRails', 'Tech'),
('Pecan', 'Tech'),
('Similarweb', 'Tech'),
('Fireblocks', 'Cybersecurity'),
('Appsflyer', 'Tech'),
('Taboola', 'Tech'),
('MoonActive', 'Gaming'),
('Jfrog', 'Tech'),
('Yotpo', 'Tech'),
('Riskified', 'Tech'),
('Outbrain', 'Tech'),
('Logz.io', 'Tech'),
('Helios', 'Tech'),
('Via', 'Tech'),
('Simply', 'Tech'),
('Proofpoint', 'Cybersecurity'),
('Singular', 'Tech'),
('Melio', 'FinTech'),
('Unity', 'Gaming'),
('WalkMe', 'Tech'),
('Fiverr', 'Tech'),
-- From Page 2
('BigPanda', 'Tech'),
('DoiT International', 'Tech'),
('Connecteam', 'Tech'),
('Dynamic Yield', 'Tech'),
('Sisense', 'Tech'),
('F5', 'Tech'),
('Liveperson', 'Tech'),
('Papaya Gaming', 'Gaming'),
('MyHeritage', 'Tech'),
('Natural Intelligence', 'Tech'),
('Kaltura', 'Tech'),
('SundaySky', 'Tech'),
('Gett', 'Tech'),
('Trullion', 'Tech'),
('Amobee', 'Tech'),
('Tango', 'Tech'),
('Gong', 'Tech'),
('Autodesk', 'Tech'),
('Tipalti', 'FinTech'),
('Chorus.ai', 'Tech'),
('Fundbox', 'FinTech'),
('Honeybook', 'Tech'),
('Trax', 'Tech'),
('Weka.io', 'Tech'),
('Oribi', 'Tech'),
('Lemonade', 'InsurTech'),
('Rapyd', 'FinTech'),
('Pyramid Analytics', 'Tech'),
('OwnBackup', 'Tech'),
('BlueVine', 'FinTech'),
('Cybereason', 'Cybersecurity'),
-- From Page 3
('hibob', 'Tech'),
('K Health', 'HealthTech'),
('Nexar', 'Tech'),
('Snyk', 'Cybersecurity'),
('Cloudinary', 'Tech'),
('Lightricks', 'Tech'),
('Datorama', 'Tech'),
('Duda', 'Tech'),
('Vimeo', 'Tech'),
('Minute Media', 'Media'),
('Verbit', 'Tech'),
('Simplee', 'HealthTech'),
('Elementor', 'Tech'),
('Hysolate', 'Cybersecurity'),
('Intezer Labs', 'Cybersecurity'),
('Torq', 'Cybersecurity'),
('Panorays', 'Cybersecurity'),
('Sentra', 'Cybersecurity'),
('Cervello', 'Cybersecurity'),
('Grip Security', 'Cybersecurity'),
('Silverfort', 'Cybersecurity'),
('Cato', 'Cybersecurity'),
('SentinelOne', 'Cybersecurity'),
('Zscaler (Avalor)', 'Cybersecurity'),
('Apiiro', 'Cybersecurity'),
('Talon', 'Cybersecurity'),
('Palo Alto', 'Cybersecurity'),
('DeepInstinct', 'Cybersecurity'),
('At-Bay', 'InsurTech'),
('Skybox Security', 'Cybersecurity'),
-- From Page 4 (Cybersecurity companies)
('Aqua Security', 'Cybersecurity'),
('AVANAN', 'Cybersecurity'),
('Guardicore', 'Cybersecurity'),
('Orca Security', 'Cybersecurity'),
('PerimeterX', 'Cybersecurity'),
('Salt Security', 'Cybersecurity'),
('Illusive', 'Cybersecurity'),
('Cynet Security', 'Cybersecurity'),
('Perimeter 81', 'Cybersecurity'),
('CyberArk', 'Cybersecurity'),
('Forescout', 'Cybersecurity'),
('Tufin', 'Cybersecurity'),
('Argus', 'Cybersecurity'),
('Cyera', 'Cybersecurity'),
('Wiz', 'Cybersecurity'),
('Prompt Security', 'Cybersecurity'),
('Active Fence', 'Cybersecurity'),
('Apono', 'Cybersecurity'),
('Axiom Security', 'Cybersecurity'),
('Axis Security', 'Cybersecurity'),
('Axonius', 'Cybersecurity'),
('Clarity', 'Cybersecurity'),
('CYE', 'Cybersecurity'),
('CyCognito', 'Cybersecurity'),
('OX Security', 'Cybersecurity'),
('CyCode', 'Cybersecurity'),
('Cylus', 'Cybersecurity'),
('Cyren', 'Cybersecurity'),
('enSilo', 'Cybersecurity'),
('Ermetic', 'Cybersecurity'),
-- From Page 5
('GK8', 'Cybersecurity'),
('Gurdio', 'Cybersecurity'),
('Hunters', 'Cybersecurity'),
('Ionix', 'Cybersecurity'),
('Ironscales', 'Cybersecurity'),
('Jit Security', 'Cybersecurity'),
('Kodem Security', 'Cybersecurity'),
('Koverr', 'Cybersecurity'),
('Legit Security', 'Cybersecurity'),
('Mend', 'Cybersecurity'),
('Mesh Security', 'Cybersecurity'),
('Mitiga', 'Cybersecurity'),
('Morphisec', 'Cybersecurity'),
('Nagomi Security', 'Cybersecurity'),
('nsKnox', 'Cybersecurity'),
('NSO', 'Cybersecurity'),
('Oasis Security', 'Cybersecurity'),
('Oligo Security', 'Cybersecurity'),
('Otorio', 'Cybersecurity'),
('Paragon', 'Cybersecurity'),
('Pentera', 'Cybersecurity'),
('Perception Point', 'Cybersecurity'),
('Polar Security', 'Cybersecurity'),
('Seemplicity', 'Cybersecurity'),
('Semperis', 'Cybersecurity'),
('ShieldIOT', 'Cybersecurity'),
('Solvo', 'Cybersecurity'),
('Trustmi.ai', 'Cybersecurity'),
('Upstream Security', 'Cybersecurity'),
('Upwind Security', 'Cybersecurity'),
('Valence Security', 'Cybersecurity'),
-- From Page 6
('Voyager Labs', 'Cybersecurity'),
('Vulcan Security', 'Cybersecurity'),
('Zero Networks', 'Cybersecurity'),
('CheckPoint', 'Cybersecurity'),
('Algosec', 'Cybersecurity'),
('PlainID', 'Cybersecurity'),
('SafeBreach', 'Cybersecurity'),
('Cato Networks', 'Cybersecurity'),
('Transmit Security', 'Cybersecurity'),
('IntSights', 'Cybersecurity'),
('ImmunAI', 'Cybersecurity'),
('Cynet', 'Cybersecurity'),
('Duality Technologies', 'Cybersecurity'),
('Monogoto', 'Tech'),
('Veego', 'Tech'),
('Nym', 'Cybersecurity'),
('CheckMarx', 'Cybersecurity'),
('Rapid7', 'Cybersecurity'),
('WhiteSource', 'Cybersecurity'),
('Curv', 'Cybersecurity'),
('Armis', 'Cybersecurity'),
('Claroty', 'Cybersecurity'),
('Guardknox', 'Cybersecurity'),
('ThetaRay', 'Cybersecurity'),
('Deep Instinct', 'Cybersecurity'),
('BlueVoyant', 'Cybersecurity'),
('Guardz', 'Cybersecurity'),
('Laminar', 'Cybersecurity'),
('Dazz', 'Cybersecurity'),
('Medigate', 'Cybersecurity'),
-- From Page 7
('Tenable', 'Cybersecurity'),
('XM Cyber', 'Cybersecurity'),
('CrowdStrike', 'Cybersecurity'),
('Sygnia', 'Cybersecurity'),
('Cyberbit', 'Cybersecurity'),
('Mesh Payments', 'FinTech'),
('Earnix', 'FinTech'),
('Pagaya', 'FinTech'),
('Forter', 'FinTech'),
('Jones', 'FinTech'),
('Deel', 'Tech'),
('Planck', 'InsurTech'),
('Agora', 'FinTech'),
('EverC', 'FinTech'),
('Sunbit', 'FinTech'),
('Anchor', 'FinTech'),
('Anecdotes', 'Tech'),
('April', 'InsurTech'),
('Assured Allies', 'InsurTech'),
('Behalf', 'FinTech'),
('Blue Dot', 'Tech'),
('Capitolis', 'FinTech'),
('ChargeAfter', 'FinTech'),
('Fibo', 'FinTech'),
-- From Page 8
('Finout', 'FinTech'),
('FundGuard', 'FinTech'),
('Guesty', 'Tech'),
('Lama AI', 'Tech'),
('Ledge Tech', 'Tech'),
('Stampli', 'Tech'),
('Global-e', 'Tech'),
('Nayax', 'FinTech'),
('Sayata', 'InsurTech'),
('Payem', 'FinTech'),
('Personetics', 'FinTech'),
('Papaya Global', 'Tech'),
('PayPal', 'FinTech'),
('eBay', 'Tech'),
('Citi', 'FinTech'),
('Next Insurance', 'InsurTech'),
('Nuvei', 'FinTech'),
('Simplex', 'FinTech'),
('Flywire', 'FinTech'),
('Cross River', 'FinTech'),
('Finaro', 'FinTech'),
('Traiana', 'FinTech'),
('Panax', 'FinTech'),
-- From Page 9
('Weka', 'Tech'),
('SQream', 'Tech'),
('VAST Data', 'Tech'),
('Explorium', 'Tech'),
('Pinecone', 'Tech'),
('Datadog', 'Tech'),
('Riseup', 'Tech'),
('Varonis', 'Cybersecurity'),
('Pipl', 'Tech'),
('Verbit.ai', 'Tech'),
('WSC Sports', 'Media'),
('Vidazoo', 'Media'),
('Agmatix', 'Tech'),
('Incredibuild', 'Tech'),
-- From Page 10
('Viz.ai', 'HealthTech'),
('Controlup', 'Tech'),
('Augury', 'Tech'),
('Zoomin', 'Tech'),
('TytoCare', 'HealthTech'),
('Namogoo', 'Tech'),
('NextSilicon', 'Tech'),
('Beyond Minds', 'Tech'),
('Cheq', 'Tech'),
('Bringg', 'Tech'),
('Qwilt', 'Tech'),
('Zencity', 'Tech'),
('Bizzabo', 'Tech'),
('Healthy.io', 'HealthTech'),
('Ukko', 'Tech'),
('Pliops', 'Tech'),
('Granulate', 'Tech'),
('Gigantic', 'Tech'),
('Mine', 'Tech'),
('Run:AI', 'Tech'),
('Juganu', 'Tech'),
('Wiliot', 'Tech'),
('Deci', 'Tech'),
-- From Page 11
('Theator', 'HealthTech'),
('Soos Technology', 'Tech'),
('AccessiBe', 'Tech'),
('Dialogue', 'Tech'),
('Satori Cyber', 'Cybersecurity'),
('OneView', 'Tech'),
('Coralogix', 'Tech'),
('Redis', 'Tech'),
('ZipRecruiter', 'Tech'),
('Versatile', 'Tech'),
('Google', 'Tech'),
('Meta', 'Tech'),
-- From Page 12
('Amazon', 'Tech'),
('Microsoft', 'Tech'),
('Nvidia', 'Tech'),
('Apple', 'Tech'),
('Waze', 'Tech'),
('Dropbox', 'Tech'),
('Salesforce', 'Tech'),
('NetApp', 'Tech'),
('SolarWinds', 'Tech'),
('Anaplan', 'Tech'),
('Booking.com', 'Tech'),
('New Relic', 'Tech'),
('8fig', 'Tech'),
('Affogata', 'Tech'),
('AI-Signals', 'Tech'),
('AI21 Labs', 'Tech'),
('Aidoc', 'HealthTech'),
('AIify', 'Tech'),
('AIio', 'Tech'),
('AIlabs', 'Tech'),
('AIlink', 'Tech'),
('AIlytics', 'Tech'),
('Aim Security', 'Cybersecurity'),
('AImatic', 'Tech'),
('AInet', 'Tech'),
('AInode', 'Tech'),
('AInow', 'Tech'),
('Air Doctor', 'HealthTech'),
('AISAP', 'Tech'),
('AIsense', 'Tech'),
('AIspark', 'Tech'),
-- From Page 13
('AIware', 'Tech'),
('AKEYLESS', 'Cybersecurity'),
('Alcide', 'Cybersecurity'),
('AlgoApps', 'Tech'),
('AllCloud', 'Tech'),
('Anagog', 'Tech'),
('AnalyticsLfz', 'Tech'),
('Annapurna Labs', 'Tech'),
('Anodot', 'Tech'),
('Any.do', 'Tech'),
('AnyVision', 'Tech'),
('Anyword', 'Tech'),
('Anzu', 'Gaming'),
('anzu.io', 'Gaming'),
('Appify', 'Tech'),
('Applabs', 'Tech'),
('Applied Systems', 'Tech'),
('Appmatic', 'Tech'),
('AppMdb', 'Tech'),
('Appmind', 'Tech'),
('Appnow', 'Tech'),
('Aquant', 'Tech'),
('Aqwise', 'Tech'),
('Arbe Robotics', 'Tech'),
('Argus Cyber Security (PlaxidityX)', 'Cybersecurity'),
('Astrix Security', 'Cybersecurity'),
('ATLASense Biomed', 'HealthTech'),
('AuditAnalytics', 'Tech'),
('Autofleet', 'Tech'),
('AutoLeadStar (Fullpath)', 'Tech'),
('Automat-IT', 'Tech'),
-- From Page 14
('AutomaticFlows', 'Tech'),
('Autonomous Pivot', 'Tech'),
('Autotalks', 'Tech'),
('Avertto', 'Tech'),
('Axonize', 'Tech'),
('Balance', 'FinTech'),
('Beam', 'Tech'),
('Become', 'Tech'),
('BEEWISE', 'Tech'),
('Beti', 'Tech'),
('Better Leaf', 'Tech'),
('BetterTogether', 'Tech'),
('BeyondMinds', 'Tech'),
('BigID', 'Cybersecurity'),
('Binah.ai', 'HealthTech'),
('BioCatch', 'Cybersecurity'),
('Biokine Therapeutics', 'HealthTech'),
('BlazeMeter', 'Tech'),
('Bllink', 'Tech'),
('Blockaid', 'Cybersecurity'),
('Blue White Robotics', 'Tech'),
('Bluewhite', 'Tech'),
('Bookaway', 'Tech'),
('BreezoMeter', 'Tech'),
('BRIA.ai', 'Tech'),
('Bridgecrew', 'Cybersecurity'),
('Bright Data', 'Tech'),
('Buildots', 'Tech'),
('CardinalOps', 'Cybersecurity'),
('Cellebrite', 'Tech'),
('Check Point', 'Cybersecurity'),
-- From Page 15
('Cider Security', 'Cybersecurity'),
('Clawdia.AI', 'Tech'),
('Cloudify', 'Tech'),
('cnvrg.io', 'Tech'),
('Cognata', 'Tech'),
('CyberX', 'Cybersecurity'),
('Cyolo', 'Cybersecurity'),
('D-ID', 'Tech'),
('Darrow', 'Tech'),
('Darrow AI', 'Tech'),
('Databand', 'Tech'),
('Databits', 'Tech'),
('DataCxj', 'Tech'),
('Dataify', 'Tech'),
('Dataloop', 'Tech'),
('dataloop.ai', 'Tech'),
('Descope', 'Tech'),
('Diagnostic Robotics', 'HealthTech'),
('Dome9 (Acquired by Check Point)', 'Cybersecurity'),
('Dream', 'Tech'),
('EasySend', 'Tech'),
('Entro Security', 'Cybersecurity'),
('env0', 'Tech'),
('Eon', 'Tech'),
('Epsagon', 'Tech'),
('Fabric', 'Tech'),
('Final', 'Tech'),
('Frontegg', 'Tech'),
('Fyber', 'Tech'),
('Ginnie AI', 'Tech'),
('GK8 by Galaxy', 'Cybersecurity'),
-- From Page 16
('Glassbox', 'Tech'),
('Grain', 'Tech'),
('Greeneye', 'Tech'),
('Guardio', 'Cybersecurity'),
('Habana Labs', 'Tech'),
('Hailo', 'Tech'),
('Identiq', 'Tech'),
('Iguazio', 'Tech'),
('Illusive Networks', 'Cybersecurity'),
('Ilyon', 'Tech'),
('Intel Israel', 'Tech'),
('Intezer', 'Cybersecurity'),
('Intuition Robotics', 'Tech'),
('IronSource', 'Gaming'),
('Island', 'Cybersecurity'),
('IVIX', 'Tech'),
('Jasper', 'Tech'),
('Jifiti', 'FinTech'),
('Jit', 'Cybersecurity'),
('Jolt.io', 'Tech'),
('JoyTunes', 'Gaming'),
('Juno Journey', 'Tech'),
('Kahoona', 'Tech'),
('Karamba Security', 'Cybersecurity'),
('Kela', 'Cybersecurity'),
('KELA Cyber', 'Cybersecurity'),
('Kodem', 'Cybersecurity'),
('Komodor', 'Tech'),
('Kovrr', 'Cybersecurity'),
('Laguna', 'Tech'),
('LawGeex', 'Tech'),
-- From Page 17
('Lendbuzz', 'FinTech'),
('Lightrun', 'Tech'),
('LinearB', 'Tech'),
('Loora AI', 'Tech'),
('Loris.ai', 'Tech'),
('LSports', 'Media'),
('Lumen', 'Tech'),
('Lumigo', 'Tech'),
('Luminate Security', 'Cybersecurity'),
('Lusha', 'Tech'),
('Magisto', 'Tech'),
('Metabase', 'Tech'),
('MESH', 'Tech'),
('MineOS', 'Tech'),
('Mobileye', 'Tech'),
('monday.com', 'Tech'),
('Moovit', 'Tech'),
('Navan', 'Tech'),
('Navina', 'HealthTech'),
('Neura', 'Tech'),
('NeuReality', 'Tech'),
('Nexite', 'Tech'),
('Noma Security', 'Cybersecurity'),
('nSure.ai', 'Tech'),
('Nucleai', 'HealthTech'),
('Nucleix', 'HealthTech'),
('Nuvoton Israel', 'Tech'),
('Nym Health', 'HealthTech'),
('Obligo', 'FinTech'),
('Octopai', 'Tech'),
('OpenWeb (Spot.IM)', 'Media'),
-- From Page 18
('Optibus', 'Tech'),
('Optimove', 'Tech'),
('Orbs', 'Tech'),
('Orca AI', 'Tech'),
('Package.AI', 'Tech'),
('Panoply', 'Tech'),
('Parametrix', 'InsurTech'),
('PayKey', 'FinTech'),
('Payoneer', 'FinTech'),
('Pcysys', 'Cybersecurity'),
('Percepto', 'Tech'),
('Permit.io', 'Tech'),
('Placer.ai', 'Tech'),
('Playtika', 'Gaming'),
('Port', 'Tech'),
('Prospera', 'Tech'),
('Prospera Technologies', 'Tech'),
('proteanTecs', 'Tech'),
('Quantum Machines', 'Tech'),
('Quris', 'HealthTech'),
('Qwak', 'Tech'),
('RapidAPI', 'Tech'),
('Redefine', 'Tech'),
('Redis Labs', 'Tech'),
('Rewire', 'FinTech'),
('Robust Intelligence', 'Tech'),
('Rookout', 'Tech'),
('Runway', 'Tech'),
('Satori', 'Cybersecurity'),
('Second Nature AI', 'Tech'),
('SeeTree', 'Tech'),
-- From Page 19
('Shopic', 'Tech'),
('Sight Diagnostics', 'HealthTech'),
('Sightful', 'Tech'),
('SimilarWeb', 'Tech'),
('Sixgill', 'Cybersecurity'),
('Slice', 'Tech'),
('Sola', 'Tech'),
('Solidus Labs', 'Cybersecurity'),
('Soluto', 'Tech'),
('Speedata', 'Tech'),
('Spines', 'Tech'),
('Splitty', 'Tech'),
('Spot by NetApp', 'Tech'),
('Spot.io', 'Tech'),
('StarkWare', 'Tech'),
('Stigg', 'Tech'),
('Stream Elements', 'Gaming'),
('StreamAI', 'Tech'),
('StreamData', 'Tech'),
('StreamElements', 'Gaming'),
('Strigo', 'Tech'),
('Supersonic', 'Gaming'),
('Superwise.ai', 'Tech'),
('Syte', 'Tech'),
('Tabnine', 'Tech'),
('Taranis', 'Tech'),
('tasq.ai', 'Tech'),
('Team8', 'Cybersecurity'),
('Toka', 'Tech'),
('Trigo', 'Tech'),
('Unit', 'FinTech'),
-- From Page 20
('Upsolver', 'Tech'),
('Utila', 'Tech'),
('UVeye', 'Tech'),
('Valens', 'Tech'),
('Varada', 'Tech'),
('Vayyar', 'Tech'),
('vcita', 'Tech'),
('Voyantis', 'Tech'),
('Vulcan Cyber', 'Cybersecurity'),
('Wibbitz', 'Tech'),
('Wilco', 'Tech'),
('Windward', 'Tech'),
('Wing Security', 'Cybersecurity'),
('WiseCloud', 'Tech'),
('WiseSense', 'Tech'),
('Wisor', 'FinTech'),
('Wizer', 'Cybersecurity'),
('Workday', 'Tech'),
('XTEND', 'Tech'),
('Xyte', 'Tech'),
('Zafran', 'Cybersecurity'),
('Zebra Medical Vision', 'HealthTech'),
('Zencity 360', 'Tech'),
('ZenGo', 'FinTech'),
('Zenity', 'Cybersecurity'),
('Zero', 'FinTech'),
('Zerto', 'Tech'),
('Zooz', 'FinTech'),
('Flare', 'Cybersecurity'),
('CloudShare', 'Tech'),
('Sharegain', 'FinTech'),
-- From Page 21
('NSO Group', 'Cybersecurity'),
('Oosto', 'Tech'),
('Moon Active', 'Gaming'),
('Plarium', 'Gaming'),
('eToro', 'FinTech'),
('Noname Security', 'Cybersecurity'),
('Trax Retail', 'Tech'),
('Talon Cyber Security', 'Cybersecurity'),
('Token Security', 'Cybersecurity'),
('Fordefi', 'Cybersecurity'),
('Teragen', 'Tech'),
('Snappy', 'Tech'),
('Zafran Security', 'Cybersecurity'),
('Port ai', 'Tech'),
('Draftt', 'Tech'),
('Pontera', 'FinTech'),
('Qodo', 'Tech'),
('Wotch', 'Tech'),
-- From Page 22
('Nekuda', 'Tech'),
('ecton.io', 'Tech'),
('Play Perfect', 'Gaming'),
('FrameSecurity', 'Cybersecurity'),
('Let\''sFesti', 'Tech'),
('Sollapay', 'FinTech'),
('F.D. Disruptive data', 'Tech'),
('Dropit', 'Tech'),
('Mavens', 'Tech'),
('Sensi.AI', 'Tech'),
('Beehero', 'Tech'),
('Qspark', 'Tech'),
('Groundcover', 'Tech'),
('Aidoc Medical', 'HealthTech'),
('Colleen.ai', 'Tech'),
('Moojo.xyz', 'Tech'),
('Papaya', 'Tech'),
('xtype.io', 'Tech'),
('LakeFS', 'Tech'),
('Masterschool', 'Tech'),
('Sequence', 'Tech'),
-- From Page 23
('Emerix', 'Tech'),
('Utappy L.T.D', 'Tech'),
('MantisVision', 'Tech'),
('Coola data', 'Tech'),
('SafeDK', 'Tech'),
('Vidmind', 'Tech'),
('Roundforest', 'Tech'),
('Overwolf', 'Gaming'),
('Bitshakers', 'Tech'),
('Houzz', 'Tech'),
('Spondoolies', 'Tech'),
('Comigo', 'Tech'),
('Jungo', 'Tech'),
('Playtech', 'Gaming'),
('Tabtale', 'Gaming'),
('FTBPro', 'Tech'),
('Vonage', 'Tech'),
('Loom', 'Tech'),
('Genarator/Yeloha', 'Tech'),
('Imagine', 'Tech'),
('Streamrail', 'Tech'),
('SalesPredict SW LTD', 'Tech'),
('Sarine Technologies L.T.D', 'Tech'),
-- From Page 24
('Toonimo', 'Tech'),
('Adience', 'Tech'),
('Magisto', 'Tech'),
('Taptica', 'Tech'),
('AVG', 'Tech'),
('Carambola', 'Tech'),
('Reporty', 'Tech'),
('Jelly Button Games', 'Gaming'),
('Any.clip', 'Tech'),
('Signal.io', 'Tech'),
('Landesk', 'Tech'),
('Veribo', 'Tech'),
('Xplenty', 'Tech'),
('Gryphonet', 'Tech'),
('Depulse', 'Tech'),
('Eagle', 'Tech'),
('Zebra', 'Tech'),
('Visualead', 'Tech'),
('Ranky', 'Tech'),
('Imonomy', 'Tech'),
('Indeni', 'Tech'),
('Fanzone', 'Tech'),
('Hi.bob', 'Tech'),
('nfrnds', 'Tech'),
('Skyline.ie', 'Tech'),
('Crossrider/DefinitiMedia/Ajillion', 'Tech'),
('Clicktale', 'Tech'),
-- From Page 25
('Algomizer', 'Tech'),
('Freesbee', 'Tech'),
('Sears', 'Tech'),
('Taykey', 'Tech'),
('GE/Nurego', 'Tech'),
('Genome', 'Tech'),
('Drippler', 'Tech'),
('Infindat', 'Tech'),
('Zengaming', 'Gaming'),
('Votiro', 'Cybersecurity'),
('Sizmek', 'Tech'),
('AppTV', 'Tech'),
('Rumble', 'Tech'),
('Emedgene', 'HealthTech'),
('Startapp', 'Tech'),
('Sparkbeyond', 'Tech'),
('Lawgeex', 'Tech'),
('Beamr', 'Tech'),
('First (Eppur)', 'Tech'),
-- From Page 26
('Allegro', 'Tech'),
('Somatix', 'HealthTech'),
('Kin/Kik', 'Tech'),
('Symantec/Fireglass', 'Cybersecurity'),
('Donde search', 'Tech'),
('Prycto', 'Tech'),
('Kornit Digital', 'Tech'),
('Hotelmize', 'Tech'),
('Wear2b', 'Tech'),
('AnyClip', 'Tech'),
('GigaSpaces Technologies', 'Tech'),
('DarioHealth', 'HealthTech'),
('Bigabid', 'Tech'),
('Pagaya Investments', 'FinTech'),
('Nexar Inc.', 'Tech'),
('InSoundz', 'Tech'),
('Teridion', 'Tech'),
('AutoLeadStar', 'Tech'),
('Skyline AI', 'Tech'),
('EY', 'Tech'),
('Neura Inc.', 'Tech'),
('Data Science Group', 'Tech'),
('Feedvisor', 'Tech'),
('StartApp', 'Tech'),
('CuraLife', 'HealthTech'),
-- From Page 27
('Palantir Technologies', 'Tech'),
('Rewire.to', 'FinTech'),
('Portshift', 'Cybersecurity'),
('Aurora Labs', 'Tech'),
('Turbonomic', 'Tech'),
('Myndlift', 'HealthTech'),
('Databand.ai', 'Tech'),
('NFX', 'Tech'),
('Novartis', 'HealthTech'),
('Nice', 'Tech'),
('Dis.co', 'Tech'),
('Samsung NEXT', 'Tech'),
('ActiveFence', 'Cybersecurity'),
('Aspectiva', 'Tech'),
('Huuuge Games', 'Gaming'),
('BrainLab', 'HealthTech'),
('Lusha.co', 'Tech'),
('Simpo', 'Tech'),
('Transmit security', 'Cybersecurity'),
-- From Page 28
('EverAfter', 'Tech'),
('Bizabbo', 'Tech'),
('BigId', 'Cybersecurity'),
('Cynerio', 'Cybersecurity'),
('Acumen', 'Tech'),
('Artlist', 'Tech'),
('SecuriThings', 'Cybersecurity'),
('OpenWeb', 'Media'),
('Stoa', 'Tech'),
('ZOOZ', 'FinTech'),
('PayU', 'FinTech'),
('Nanit', 'Tech'),
('Ultra', 'Tech'),
('Voyantis', 'Tech'),
('Novidea', 'Tech'),
('Vi', 'Tech'),
('Hello Heart', 'HealthTech'),
-- From Page 29
('Taranis', 'Tech'),
('Directeam', 'Tech'),
('Autobrains', 'Tech'),
('Sweech', 'Tech'),
('Skypath', 'Tech'),
('Hexagate', 'Cybersecurity'),
('Aiola', 'Tech'),
('Env0', 'Tech'),
('Playstudious', 'Gaming'),
('Doorloop', 'Tech'),
('Bits of gold', 'FinTech'),
('Elementary data', 'Tech'),
('Sight Diagnostic', 'HealthTech'),
('Ottopia', 'Tech'),
('Nsure', 'InsurTech'),
('Earlytech', 'Tech'),
('BigID', 'Cybersecurity')
ON CONFLICT (company_name) DO NOTHING;