// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pnpualosfngrmihbvgbb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBucHVhbG9zZm5ncm1paGJ2Z2JiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg3OTMwMDMsImV4cCI6MjA3NDM2OTAwM30.gB2AxTRR7GxKlFWu0Fl2pLwabnAwW7QDRJ3OxE58eVI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});